### ISSUE TITLE
Google captcha (20 secs)

### ISSUE THREAD

**Issue by syrius01** [paralelo14/google_explorer#25]
Would there be a way to put more then 20 seconds before the captcha times out and automatically close the browser when performing a search ?

Very nice project by the way.

Thanks,

syrius01

**Comment by paralelo14** [comment]
The current time i think is 90sec.. but i'm working in something else to work around this captcha.. next merge will come with this update..

**Comment by syrius01** [comment]
Awesome. Is there a way I can contact you in private ?

Thanks,

syrius01
