### ISSUE TITLE
Unable to run google explorer !

### ISSUE THREAD

**Issue by X-HAT** [paralelo14/google_explorer#27]
Hello
Im getting this error when i run google explorer :

Message: unknown error: no chrome binary at /usr/bin/google-chrome-stable
  (Driver info: chromedriver=2.29.461591 (62ebf098771772160f391d75e589dc567915b233),platform=Windows NT 6.1.7601 SP1 x86_64)

**Comment by paralelo14** [comment]
Hi my friend.. 

Some things you could do:

If you are using windows, please put the path for the google chrome binary on line 137 and check..

I didn't test it on windows.. only linux.. 

best regards,

daniel.
