### ISSUE TITLE
chromedriver error not working

### ISSUE THREAD

**Issue by jasonearly2** [paralelo14/google_explorer#29]
# python google_explorer.py --browser='chrome' --dork='site:gob.ve inurl:index.php' --location="Venezuela"
 [#] Error [#]: Error while using chromedriver.
These are some possible solutions for this issue:
 Please install/update chormedriver. Check out this link for help: https://developers.supportbee.com/blog/setting-up-cucumber-to-run-with-Chrome-on-Linux/
- Do not run the tool as root user, like is described in this issue: https://github.com/anarcoder/google_explorer/issues/2
Message: unknown error: Chrome failed to start: exited abnormally
 (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Linux 3.11.0-15-generic x86_64)
i instaled chromedriver
 locate chromedriver
./etc/ppp/chromedriver_linux64.zip
 ./usr/bin/chromedriver

**Comment by paralelo14** [comment]
by this error you need to install the chromedriver correctly.. 

./etc/ppp/chromedriver_linux64.zip   <-- you are pointing to a zip file..

check the link of the error showing the instructions of instalation..

see ya,

daniel ;))

**Comment by jasonearly2** [comment]
the@u19950823:~/ok$ chromedriver -v
ChromeDriver 2.10.267518
the@u19950823:~/ok$ python3 google_explorer.py --browser='chrome' --dork='inurl:index.php?option' --location="Rússia" --last_update='na última semana'

[#] Error [#]: Error while using chromedriver.

These are some possible solutions for this issue:
i install correctly but not working 


- Please install/update chormedriver. Check out this link for help: https://developers.supportbee.com/blog/setting-up-cucumber-to-run-with-Chrome-on-Linux/
- Do not run the tool as root user, like is described in this issue: https://github.com/anarcoder/google_explorer/issues/2


Message: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.10.267518,platform=Linux 3.13.0-116-generic x86_64)

**Comment by paralelo14** [comment]
In this case try updating the chromedriver version..  the last is 2.29.. i'm using the 2.27..

There are some problems with these versions between browsers, specially chrome.. i personally use chromium..

If you want to keep this version, you can try run with other browser.. i suggest you give a try in chromium..

**Comment by jasonearly2** [comment]
the@u19950823:~/ok$ python3 google_explorer.py --browser='chromium' --dork='inurl:index.php?option' --location="Rússia" --last_update='na última semana'

[#] Error [#]: Error while using chromedriver.

These are some possible solutions for this issue:

- Please install/update chormedriver. Check out this link for help: https://developers.supportbee.com/blog/setting-up-cucumber-to-run-with-Chrome-on-Linux/
- Do not run the tool as root user, like is described in this issue: https://github.com/anarcoder/google_explorer/issues/2


Message: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.27.440175 (9bc1d90b8bfa4dd181fbbf769a5eb5e575574320),platform=Linux 3.13.0-116-generic x86_64)


i update chromedriver i use chromium but not work man

**Comment by paralelo14** [comment]
Humm..

can you paste here the versions of the requirements you installed?? I think if you run pip freeze it will show all of them..
