### ISSUE TITLE
unable to use script using putty ssh shell

### ISSUE THREAD

**Issue by bitniko** [paralelo14/google_explorer#32]
hi, i tried your script with Ubuntu 16.04.2 LTS python 3.6.0
im using a ssh shell via putty, when i type on the shell
google-chrome-stable
i get the error:
> [29093:29093:0511/060639.952416:ERROR:browser_main_loop.cc(279)] Gtk: cannot open display:

furthermore while trying to run the script i get the msg:

> [#] Error [#]: Error while using chromedriver.
> 
> These are some possible solutions for this issue:
> 
> - Please install/update chormedriver. Check out this link for help: https://developers.supportbee.com/blog/setting-up-cucumber-to-run-with-Chrome-on-Linux/
> - Do not run the tool as root user, like is described in this issue: https://github.com/anarcoder/google_explorer/issues/2
> 
> 
> Message: unknown error: Chrome failed to start: exited abnormally
>   (Driver info: chromedriver=2.10.267518,platform=Linux 4.4.0-62-generic x86_64)

my question is, is it possible to run your script under a ssh shell?
thanks.

**Comment by paralelo14** [comment]
The way it is coded now is not possible.. but you can fork the project and implement this feature using a plugin called Xvfb, that simulates a screen, so the is possible to render the browser... But doing this way, you will not be able to deel with the google captcha.. so i dont't think is a good idea.

good luck

daniel
