### ISSUE TITLE
I dont find features/support/env.rb

### ISSUE THREAD

**Issue by hackituria** [paralelo14/google_explorer#38]
When I want install Chromedriver I don't find features/support/env.rb to add the code.

**Comment by 4chr4f** [comment]
same here

**Comment by 4chr4f** [comment]
after installing cucumber with # gem install cucumber
then starting it with # cucumber --init 
give result as 
create   features
  create   features/step_definitions
  create   features/support
  create   features/support/env.rb
then you can type # locate features/support/ to show the folders under the same name and you can edit your # features/support/env.rb
hope it's clear enough 
happy hunting
