### ISSUE TITLE
script doesn't write output to results_google_search.txt

### ISSUE THREAD

**Issue by bitniko** [paralelo14/google_explorer#50]
hello,

script google_explorer.py doesn't write output of parsed links to results_google_search.txt..

what could be wrong?
stop working, decided to do fresh OS install, install python 3.6.0 and its deps but does not save results...

Thanks

**Comment by paralelo14** [comment]
humm sorry for that.. i will checkout what could make this happen.. here is still working.. what linux are you using?

**Comment by bitniko** [comment]
Ubuntu minimal 64bits..

what could be the problem? permissions?
can you test?

Thanks

**Comment by paralelo14** [comment]
Strange, im using ubuntu 64 too.. what google domain are you using for the search? try using google.com.br as --google_domain argument just to check if the xpath for the results parsing are working

**Comment by bitniko** [comment]
ive replaced chromedriver to latest seems to work better...
but after it says:
"parsing links from page.."
it doesnt write output of results to results_google_search.txt ... what can be the problem? tried to chmod txt file, tried to put some strings on it and then run the tool, and even tried to delete txt file and run the tool to see if created the file with results.. nothing :(

**Comment by paralelo14** [comment]
the problem is the XPATH of the links in google results, the current xpath is working with firefox.. you can use firefox insted of chrome.. to do this you should install geckodriver the same way you install chromedriver..

**Comment by paralelo14** [comment]
I make the fix now, please pull the update and try again =)
