### ISSUE TITLE
License

### ISSUE THREAD

**Issue by xorond** [paralelo14/google_explorer#9]
Hello,

I'd like to add your tool into [ArchStrike](https://github.com/ArchStrike/ArchStrike) but it looks like your tool doesn't have a license.

Can you add a license file?

**Comment by paralelo14** [comment]
Hi my friend,

i will add the license file... witch one is better for you? mit, gpl..

**Comment by xorond** [comment]
It's your tool, choose one as you see fit :)

**Comment by paralelo14** [comment]
the tool is ours =)) i don't have experience with these license.. is mit good for us (everyone)?

**Comment by xorond** [comment]
It is. You can see more info here https://opensource.org/licenses

**Comment by paralelo14** [comment]
like this my friend??

https://github.com/anarcoder/google_explorer/blob/beta_version/LICENSE

**Comment by xorond** [comment]
Yep.

**Comment by paralelo14** [comment]
=)

**Comment by xorond** [comment]
Thanks, I'll be adding your tool soon :)
